#!/bin/bash

export EPICS_CA_MAX_ARRAY_BYTES=4100000

# ADCore
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/areaDetector-master/ADCore/ADApp/op/ui/:/opt/epics/synApps/support/areaDetector-master/ADCore/ADApp/op/ui/autoconvert/:$CAQTDM_DISPLAY_PATH

#ADPilatus
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/areaDetector-master/ADPilatus/pilatusApp/op/ui/:/opt/epics/synApps/support/areaDetector-master/ADPilatus/pilatusApp/op/ui/autoconvert/:$CAQTDM_DISPLAY_PATH

#Asyn
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/asyn-R4-45/opi/caqtdm/:$CAQTDM_DISPLAY_PATH

#Autosave
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/autosave-R5-11/asApp/op/ui/:/opt/epics/synApps/support/autosave-R5-11/asApp/op/ui/autoconvert/:$CAQTDM_DISPLAY_PATH

caQtDM -macro "P="18IDpil1M":, R=cam1:" pilatusDetector.ui

