#!/bin/bash

pushd /opt/epics/iocs/iocEiger2

export EPICS_CA_MAX_ARRAY_BYTES=30000000

/opt/epics/synApps/support/areaDetector-R3-11/ADEiger/iocs/eigerIOC/bin/${EPICS_HOST_ARCH}/eigerDetectorApp /opt/epics/iocs/iocEiger2/st.cmd

popd

