#!/bin/bash

export EPICS_CA_MAX_ARRAY_BYTES=30000000

# ADCore
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/areaDetector-R3-11/ADCore/ADApp/op/ui/:/opt/epics/synApps/support/areaDetector-R3-11/ADCore/ADApp/op/ui/autoconvert/:$CAQTDM_DISPLAY_PATH

#ADEiger
export CAQTDM_DISPLAY_PATH=/opt/epics/synApps/support/areaDetector-R3-11/ADEiger/eigerApp/op/ui/:/opt/epics/synApps/support/areaDetector-R3-11/ADEiger/eigerApp/op/ui/autoconvert/:$CAQTDM_DISPLAY_PATH

caQtDM -macro "P="18ID:EIG2":, R=cam1:" eiger2Detector.ui

