#!/bin/bash

pushd /opt/epics/epics_iocs/soft_iocs/marCCD

export EPICS_CA_MAX_ARRAY_BYTES=9000000

/opt/epics/synApps/support/areaDetector-master/ADmarCCD/iocs/marCCDIOC/bin/${EPICS_HOST_ARCH}/marCCDApp ./st.cmd

popd

