#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../../.. T_A=vxWorks694-ppc32  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../../.. T_A=vxWorks694-ppc32  $@

force:  ;
